name: Build & Deploy Jekyll to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2) Use ruby/setup-ruby, which handles Ruby installation and caching
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"      # Change to whatever Ruby version you need
          bundler-cache: true      # Speeds up subsequent runs by caching gems

      # 3) Install your Gemfile dependencies
      - name: Install dependencies
        run: |
          bundle install

      # 4) Build your Jekyll site
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --trace --destination _site

      # 5) Upload the generated site as an artifact
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site  # Matches the --destination _site above

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
